name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Add DO Droplet to SSH known hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.HOST }} $(ssh-keyscan ${{ secrets.HOST }} 2>/dev/null)" >> ~/.ssh/known_hosts

    - name: Deploy to DigitalOcean
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "$SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r * ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIRECTORY }}
        ssh -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rsync -avz --delete ./out ${{ secrets.TARGET_DIRECTORY }}"
        rm -f private_key.pem
