name: Build and Deploy


on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Next.js site
        run: npm install && npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: './out/*'
          target: ${{ secrets.TARGET_DIRECTORY }}

      - name: Restart server (if needed)
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart nginx'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
