name: Build and Deploy


on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build

      - name: Add DO Droplet to SSH known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.HOST }} $(ssh-keyscan ${{ secrets.HOST }} 2>/dev/null)" >> ~/.ssh/known_hosts'

      - name: Deploy to DigitalOcean
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r * ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/${{ secrets.TARGET_DIRECTORY }}
          ssh -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rsync -avz --delete ./out ${{ secrets.TARGET_DIRECTORY }}"
          rm -f private_key.pem

